#!/usr/bin/env python3
"""
generate_seed.py — Generate supabase/seed.sql from scheme JSON data.

Usage:
    python3 scripts/generate_seed.py

Reads:
    data/schemes/*.json

Writes:
    supabase/seed.sql

Produces a valid PostgreSQL seed file that:
- Generates deterministic UUIDs from scheme_code
- Inserts into schemes, scheme_rules, scheme_documents,
  tutorial_steps, scheme_verification, scheme_profile_fields
- Uses ON CONFLICT DO NOTHING for idempotency
- Contains no fabricated data (only what's in the JSON files)

Exit code 0 = success, 1 = errors.
"""

import json
import sys
import uuid
import re
from pathlib import Path
from datetime import datetime

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
SCHEMES_DIR = DATA_DIR / "schemes"
OUTPUT_FILE = PROJECT_ROOT / "supabase" / "seed.sql"


def deterministic_uuid(seed: str) -> str:
    """Generate a deterministic UUID v5 from a seed string."""
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"yojana-setu-scheme:{seed}"))


def escape_sql(value) -> str:
    """Escape a value for PostgreSQL single-quoted literal."""
    if value is None:
        return "NULL"
    s = str(value)
    s = s.replace("\\", "\\\\")
    s = s.replace("'", "''")
    return f"'{s}'"


def escape_jsonb(value) -> str:
    """Serialize a value as a JSONB literal for PostgreSQL."""
    return escape_sql(json.dumps(value, ensure_ascii=False))


def format_timestamp(iso_str: str) -> str:
    """Format an ISO timestamp for PostgreSQL."""
    return escape_sql(iso_str)


def format_date(date_str: str) -> str:
    """Format a date string for PostgreSQL."""
    return escape_sql(date_str)


def main():
    errors = []
    lines = []

    lines.append("-- Auto-generated by scripts/generate_seed.py")
    lines.append(f"-- Generated at: {datetime.utcnow().isoformat()}Z")
    lines.append("-- Do NOT edit manually.")
    lines.append("")

    # Find scheme files
    if not SCHEMES_DIR.exists():
        SCHEMES_DIR.mkdir(parents=True, exist_ok=True)

    scheme_files = sorted(SCHEMES_DIR.glob("*.json"))

    if not scheme_files:
        lines.append("-- No scheme data files found. Seed file is intentionally empty.")
        OUTPUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print("No scheme files found. Generated empty seed.sql.")
        return 0

    # Track all scheme UUIDs for FK references
    scheme_uuids = {}

    for sf in scheme_files:
        filename = sf.name
        try:
            data = json.loads(sf.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            errors.append(f"[{filename}] Invalid JSON: {e}")
            continue

        scheme_code = data.get("scheme_code", sf.stem)
        scheme_id = deterministic_uuid(scheme_code)
        scheme_uuids[scheme_code] = scheme_id

        # --- schemes ---
        lines.append(f"-- Scheme: {scheme_code}")
        lines.append("INSERT INTO schemes (")
        lines.append("    id, scheme_code, name, description, ministry, department,")
        lines.append("    scheme_type, status, aliases, target_groups, tags, benefits,")
        lines.append("    official_url, effective_from, effective_to, last_verified_at")
        lines.append(") VALUES (")
        lines.append(f"    {escape_sql(scheme_id)}::uuid,")
        lines.append(f"    {escape_sql(scheme_code)},")
        lines.append(f"    {escape_sql(data.get('name', ''))},")
        lines.append(f"    {escape_sql(data.get('description', ''))},")
        lines.append(f"    {escape_sql(data.get('ministry', ''))},")
        lines.append(f"    {escape_sql(data.get('department', ''))},")
        lines.append(f"    {escape_sql(data.get('scheme_type', 'other'))},")
        lines.append(f"    {escape_sql(data.get('status', 'active'))},")
        lines.append(f"    {escape_jsonb(data.get('aliases', []))}::jsonb,")
        lines.append(f"    {escape_jsonb(data.get('target_groups', []))}::jsonb,")
        lines.append(f"    {escape_jsonb(data.get('tags', []))}::jsonb,")
        lines.append(f"    {escape_jsonb(data.get('benefits', []))}::jsonb,")
        lines.append(f"    {escape_sql(data.get('official_url'))},")
        lines.append(f"    {format_date(data.get('effective_from', '2025-01-01'))},")
        lines.append(f"    {format_date(data.get('effective_to'))},")
        lines.append(f"    {format_timestamp(data.get('last_verified_at', datetime.utcnow().isoformat() + 'Z'))}")
        lines.append(") ON CONFLICT (scheme_code) DO NOTHING;")
        lines.append("")

        # --- scheme_rules ---
        for rule in data.get("rules", []):
            rule_id = deterministic_uuid(f"{scheme_code}:rule:{rule.get('field', '')}:{rule.get('operator', '')}:{rule.get('rule_group', '')}")
            lines.append("INSERT INTO scheme_rules (")
            lines.append("    id, scheme_id, rule_group, field, operator, value, description, rule_purpose")
            lines.append(") VALUES (")
            lines.append(f"    {escape_sql(rule_id)}::uuid,")
            lines.append(f"    {escape_sql(scheme_id)}::uuid,")
            lines.append(f"    {escape_sql(rule.get('rule_group', ''))},")
            lines.append(f"    {escape_sql(rule.get('field', ''))},")
            lines.append(f"    {escape_sql(rule.get('operator', ''))},")
            lines.append(f"    {escape_jsonb(rule.get('value'))}::jsonb,")
            lines.append(f"    {escape_sql(rule.get('description', ''))},")
            lines.append(f"    'eligibility'")
            lines.append(") ON CONFLICT (id) DO NOTHING;")
            lines.append("")

        # --- scheme_rules (exclusion) ---
        for rule in data.get("exclusion_rules", []):
            rule_id = deterministic_uuid(f"{scheme_code}:exclusion:{rule.get('field', '')}:{rule.get('operator', '')}:{rule.get('rule_group', '')}")
            lines.append("INSERT INTO scheme_rules (")
            lines.append("    id, scheme_id, rule_group, field, operator, value, description, rule_purpose")
            lines.append(") VALUES (")
            lines.append(f"    {escape_sql(rule_id)}::uuid,")
            lines.append(f"    {escape_sql(scheme_id)}::uuid,")
            lines.append(f"    {escape_sql(rule.get('rule_group', ''))},")
            lines.append(f"    {escape_sql(rule.get('field', ''))},")
            lines.append(f"    {escape_sql(rule.get('operator', ''))},")
            lines.append(f"    {escape_jsonb(rule.get('value'))}::jsonb,")
            lines.append(f"    {escape_sql(rule.get('description', ''))},")
            lines.append(f"    'exclusion'")
            lines.append(") ON CONFLICT (id) DO NOTHING;")
            lines.append("")

        # --- scheme_documents ---
        for doc in data.get("documents", []):
            doc_id = deterministic_uuid(f"{scheme_code}:doc:{doc.get('document_type', '')}:{doc.get('document_name', '')}")
            lines.append("INSERT INTO scheme_documents (")
            lines.append("    id, scheme_id, document_type, document_name, is_mandatory, description")
            lines.append(") VALUES (")
            lines.append(f"    {escape_sql(doc_id)}::uuid,")
            lines.append(f"    {escape_sql(scheme_id)}::uuid,")
            lines.append(f"    {escape_sql(doc.get('document_type', 'other'))},")
            lines.append(f"    {escape_sql(doc.get('document_name', ''))},")
            lines.append(f"    {'true' if doc.get('is_mandatory', True) else 'false'},")
            lines.append(f"    {escape_sql(doc.get('description'))}")
            lines.append(") ON CONFLICT (id) DO NOTHING;")
            lines.append("")

        # --- tutorial_steps ---
        for step in data.get("tutorial_steps", []):
            step_id = deterministic_uuid(f"{scheme_code}:step:{step.get('step_number', 0)}")
            lines.append("INSERT INTO tutorial_steps (")
            lines.append("    id, scheme_id, step_number, title, description, tips")
            lines.append(") VALUES (")
            lines.append(f"    {escape_sql(step_id)}::uuid,")
            lines.append(f"    {escape_sql(scheme_id)}::uuid,")
            lines.append(f"    {step.get('step_number', 1)},")
            lines.append(f"    {escape_sql(step.get('title', ''))},")
            lines.append(f"    {escape_sql(step.get('description', ''))},")
            lines.append(f"    {escape_sql(step.get('tips'))}")
            lines.append(") ON CONFLICT (scheme_id, step_number) DO NOTHING;")
            lines.append("")

        # --- scheme_verification ---
        verification_method_counts = {}
        for v in data.get("verification", []):
            verification_method = v.get("verification_method", "")
            verification_method_counts[verification_method] = verification_method_counts.get(verification_method, 0) + 1
            occurrence = verification_method_counts[verification_method]
            verification_seed = f"{scheme_code}:verification:{verification_method}"
            if occurrence > 1:
                verification_seed = f"{verification_seed}:{occurrence}"
            v_id = deterministic_uuid(verification_seed)
            lines.append("INSERT INTO scheme_verification (")
            lines.append("    id, scheme_id, verification_method, verification_url, helpline_number, last_verified_at, notes")
            lines.append(") VALUES (")
            lines.append(f"    {escape_sql(v_id)}::uuid,")
            lines.append(f"    {escape_sql(scheme_id)}::uuid,")
            lines.append(f"    {escape_sql(v.get('verification_method', 'online'))},")
            lines.append(f"    {escape_sql(v.get('verification_url'))},")
            lines.append(f"    {escape_sql(v.get('helpline_number'))},")
            lines.append(f"    {format_timestamp(v.get('last_verified_at', datetime.utcnow().isoformat() + 'Z'))},")
            lines.append(f"    {escape_sql(v.get('notes'))}")
            lines.append(") ON CONFLICT (id) DO NOTHING;")
            lines.append("")

        # --- scheme_profile_fields ---
        for pf in data.get("profile_fields", []):
            pf_id = deterministic_uuid(f"{scheme_code}:pf:{pf.get('field_name', '')}")
            lines.append("INSERT INTO scheme_profile_fields (")
            lines.append("    id, scheme_id, field_name, field_type, is_required, allowed_values, description")
            lines.append(") VALUES (")
            lines.append(f"    {escape_sql(pf_id)}::uuid,")
            lines.append(f"    {escape_sql(scheme_id)}::uuid,")
            lines.append(f"    {escape_sql(pf.get('field_name', ''))},")
            lines.append(f"    {escape_sql(pf.get('field_type', 'text'))},")
            lines.append(f"    {'true' if pf.get('is_required', True) else 'false'},")
            lines.append(f"    {escape_jsonb(pf.get('allowed_values'))}::jsonb,")
            lines.append(f"    {escape_sql(pf.get('description'))}")
            lines.append(") ON CONFLICT (scheme_id, field_name) DO NOTHING;")
            lines.append("")

    # Write output
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

    if errors:
        print(f"Generated seed.sql with {len(errors)} error(s):")
        for e in errors:
            print(f"  {e}")
        return 1

    print(f"Generated {OUTPUT_FILE} with {len(scheme_files)} scheme(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
